# Generated by Django 4.2.19 on 2025-03-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_alter_articleinfo_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='desc',
            field=models.TextField(null=True, verbose_name='描述'),
        ),
    ]
