# Generated by Django 4.2.19 on 2025-03-12 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_alter_articleinfo_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleinfo',
            name='desc',
            field=models.TextField(null=True, verbose_name='描述'),
        ),
    ]
