# Generated by Django 4.2.19 on 2025-03-12 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_alter_articleinfo_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleinfo',
            name='desc',
        ),
    ]
