# Generated by Django 4.2.19 on 2025-03-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0008_articleinfo_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
    ]
