# Generated by Django 4.2.19 on 2025-03-14 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.category', verbose_name='分类'),
            preserve_default=False,
        ),
    ]
