# Generated by Django 4.2.19 on 2025-03-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_articleinfo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleinfo',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='images/article/cover/'),
        ),
    ]
